[package]
name = "dploy"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.4.10", features = ["derive"] }
keyring = { version = "2.1.0", default-features = false, features=[ "linux-no-secret-service" ] }
rpassword = "7.3.1"